#!/usr/bin/env bash

source /etc/package/package.conf
source $PACKAGE_LIB

SQL_INSERT='''
INSERT INTO packages (package,timestamp,checksum,type,path)
VALUES (?, ?, ?, ?, ?);
'''

TIMESTAMP=$(date -R)
$BINDIR/package_query "$DATABASE" "$SQL_INSERT" 'package' "$TIMESTAMP" NULL 'directory' '/etc/package'
$BINDIR/package_query "$DATABASE" "$SQL_INSERT" 'package' "$TIMESTAMP" NULL 'file' '/etc/package/package.conf'
$BINDIR/package_query "$DATABASE" "$SQL_INSERT" 'package' "$TIMESTAMP" NULL 'file' '/usr/local/lib/libpackage.sh'
$BINDIR/package_query "$DATABASE" "$SQL_INSERT" 'package' "$TIMESTAMP" NULL 'file' '/usr/local/bin/package_check'
$BINDIR/package_query "$DATABASE" "$SQL_INSERT" 'package' "$TIMESTAMP" NULL 'file' '/usr/local/bin/package_list'
$BINDIR/package_query "$DATABASE" "$SQL_INSERT" 'package' "$TIMESTAMP" NULL 'file' '/usr/local/bin/package_uninstall'
$BINDIR/package_query "$DATABASE" "$SQL_INSERT" 'package' "$TIMESTAMP" NULL 'file' '/usr/local/bin/package_init'
$BINDIR/package_query "$DATABASE" "$SQL_INSERT" 'package' "$TIMESTAMP" NULL 'file' '/usr/local/bin/package_install'
$BINDIR/package_query "$DATABASE" "$SQL_INSERT" 'package' "$TIMESTAMP" NULL 'file' '/usr/local/bin/package_whatprovides'
$BINDIR/package_query "$DATABASE" "$SQL_INSERT" 'package' "$TIMESTAMP" NULL 'file' '/usr/local/bin/package_query'




#end of file
