#!/usr/bin/env bash

# load config
# {{{
PACKAGE_CONF="${PACKAGE_CONF:-/etc/package/package.conf}"
if [ ! -f "$PACKAGE_CONF" ]; then
    echo "error: cannot find $PACKAGE_CONF" >&2
    exit 1
fi
source $PACKAGE_CONF

# load library
if [ -z "$PACKAGE_LIB" -o ! -f "$PACKAGE_LIB" ]; then
    echo 'error: cannot load shared lib PACKAGE_LIB, check package.conf' >&2
    exit 1
fi
source $PACKAGE_LIB
# }}}

# initialize the package database
SQL_CREATE_TABLE='''
CREATE TABLE IF NOT EXISTS packages (
    id        INTEGER PRIMARY KEY ASC AUTOINCREMENT,
    package   TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    path      TEXT NOT NULL UNIQUE,
    type      TEXT NOT NULL,
    checksum  TEXT DEFAULT NULL);
'''

log_debug "Executing SQLite3 statment: $SQL_CREATE_TABLE"

install -d -m 755 $(dirname "$DATABASE")
$BINDIR/package_query "$DATABASE" "$SQL_CREATE_TABLE"

log_verbose "Initialized package database in $DATABASE"

# vim: fdm=marker
# end of file
