#!/usr/bin/env bash

# load config
# {{{
PACKAGE_CONF='/etc/package/package.conf'
if [ ! -f "$PACKAGE_CONF" ]; then
    echo 'error: cannot find $PACKAGE_CONF' >&2
    exit 1
fi
source $PACKAGE_CONF

# load library
if [ -z "$PACKAGE_LIB" -o ! -f "$PACKAGE_LIB" ]; then
    echo 'error: cannot load shared lib PACKAGE_LIB, check package.conf' >&2
    exit 1
fi
source $PACKAGE_LIB
# }}}

# list installed packages
SQL_WHATPROVIDES='''
SELECT DISTINCT package
FROM packages
WHERE path = ?;
'''

SEARCH_PATH=$(realpath -es $1)
$BINDIR/package_query "$DATABASE" "$SQL_WHATPROVIDES" "$SEARCH_PATH"


# vim: fdm=marker
# end of file
