#!/usr/bin/env bash

# load config
# {{{
PACKAGE_CONF="${PACKAGE_CONF:-/etc/package/package.conf}"
if [ ! -f "$PACKAGE_CONF" ]; then
    echo "error: cannot find $PACKAGE_CONF" >&2
    exit 1
fi
source $PACKAGE_CONF

# load library
if [ -z "$PACKAGE_LIB" -o ! -f "$PACKAGE_LIB" ]; then
    echo 'error: cannot load shared lib PACKAGE_LIB, check package.conf' >&2
    exit 1
fi
source $PACKAGE_LIB
# }}}

PACKAGE_NAME=$1
PACKAGE_ROOT=$(readlink -es ${2:-.})'/'
INSTALL_ROOT=$ROOT_PATH

PACKAGE_DB_ONLY="${PACKAGE_DB_ONLY:-n}"
PACKAGE_OVERWRITE="${PACKAGE_OVERWRITE:-n}"

TIMESTAMP=$(date -R)

# protected system directories + files
protected_dirs=()
while read -r protected_dir; do
    protected_dirs+=(":$protected_dir:")
done < $PROTECTED_FOLDERS_FILE

# stage 1 - collect information about packages
log_debug "stage 1: collecting information"

DIR_CACHE_FILE='.package-dir.cache'
TMP_DIR_CACHE_FILE=".tmp$DIR_CACHE_FILE"
if [ -f $DIR_CACHE_FILE ]; then
    log_verbose "using cache file - $DIR_CACHE_FILE"
else
    if [ -f "$TMP_DIR_CACHE_FILE" ]; then 
        rm "$TMP_DIR_CACHE_FILE"
    fi

    while read -r raw_package_dir; do
        package_dir=$(realpath -es "$raw_package_dir")
        install_dir=$(realpath -ms "${package_dir/#$PACKAGE_ROOT/$INSTALL_ROOT}")

        if [[ "${protected_dirs[@]}" =~ ":$install_dir:" ]]; then
            if [ -d "$install_dir" ]; then
                log_verbose "skipping system directory - $install_dir"
                continue
            else
                log_fatal "system directory does not exist - $install_dir"
                exit 1
            fi
        fi

        log_verbose "caching directory - $package_dir -> $install_dir"
        echo "$package_dir:$install_dir" >> "$TMP_DIR_CACHE_FILE"

    done <<< $(find $PACKAGE_ROOT/* -type d)
    mv "$TMP_DIR_CACHE_FILE" "$DIR_CACHE_FILE"
fi

FILE_CACHE_FILE='.package-file.cache'
TMP_FILE_CACHE_FILE=".tmp$FILE_CACHE_FILE"
if [ -f $FILE_CACHE_FILE ]; then
    log_verbose "using cache file - $FILE_CACHE_FILE"
else
    if [ -f "$TMP_FILE_CACHE_FILE" ]; then 
        rm "$TMP_FILE_CACHE_FILE"
    fi

    while read -r raw_package_file; do
        package_file=$(realpath -es "$raw_package_file")
        install_file=$(realpath -ms "${package_file/#$PACKAGE_ROOT/$INSTALL_ROOT}")

        # disallow hardlinked files
        numlinks=$(ls -ld "$package_file" |awk '{print $2}')
        if [ $numlinks -gt 1 ]; then
            log_error "skipping hardlink (unimplimented) - $package_file"
            continue
        fi

        log_verbose "caching file - $package_file -> $install_file"
        echo "$package_file:$install_file" >> "$TMP_FILE_CACHE_FILE"

    done <<< $(find $PACKAGE_ROOT/* -type f)
    mv "$TMP_FILE_CACHE_FILE" "$FILE_CACHE_FILE"
fi


if [ ! -f $DIR_CACHE_FILE ]; then
    log_fatal "failed to create directory cache"
fi

if [ ! -f $FILE_CACHE_FILE ]; then
    log_fatal "failed to create file cache"
fi

if [ ! -f $DIR_CACHE_FILE -o ! -f $FILE_CACHE_FILE ]; then
    exit 1
fi

# stage 2 - check for collisions
log_debug "stage 2: checking for colisions"

while read -r line; do
    package_dir=${line%%:*}
    install_dir=${line##*:}

    if [ ! -e "$install_dir" ]; then
        continue
    fi

    if [ -e "$install_dir" -a ! -d "$install_dir" ]; then
        filetype=$(file -b "$install_dir")
        log_error "expected directory, but got $filetype - $install_dir"
        exit 1
    fi

    package_stat=$(stat --printf='%a %U:%G' "$package_dir")
    install_stat=$(stat --printf='%a %U:%G' "$install_dir")
    if [ "x$package_stat" != "x$install_stat" ]; then
        log_warning "incorrect permissions, expected $package_stat - $install_dir"
    fi

done < $DIR_CACHE_FILE

while read -r line; do
    package_file=${line%%:*}
    install_file=${line##*:}

    if [ "x$PACKAGE_DB_ONLY" == "xy" ]; then
        continue;
    fi

    if [ -e "$install_file" ]; then
        if [ "x$PACKAGE_OVERWRITE" == "xy" ]; then
            log_warning "colision found, ignored (PACKAGE_OVERWRITE) - $install_file"
        else
            log_fatal "colision found - $install_file"
            exit 1
        fi
    fi
done < $FILE_CACHE_FILE

# stage 3 - install package
log_debug "stage 3: installing package"

SQL_INSERT='''
INSERT INTO packages (package, timestamp, path, type, checksum)
VALUES (?, ?, ?, ?, ?);
'''

while read -r line; do
    package_dir=${line%%:*}
    install_dir=${line##*:}

    if [ "x$PACKAGE_DB_ONLY" == "xn" ]; then
        install_flags=$(stat --printf='-m %a -o %u -g %g' "$package_dir")
        log_verbose "installing directory - $install_dir"
        install -d $install_flags "$install_dir"
    else
        log_verbose "skipping directory (PACKAGE_DB_ONLY) - $install_dir"
    fi

    $BINDIR/package_query "$DATABASE" "$SQL_INSERT" \
            "$PACKAGE_NAME" "$TIMESTAMP" "$install_dir" "directory" NULL

done < $DIR_CACHE_FILE

while read -r line; do
    package_file=${line%%:*}
    install_file=${line##*:}

    if [ "x$PACKAGE_DB_ONLY" == "xn" ]; then
        install_flags=$(stat --printf='-m %a -o %u -g %g' "$package_file")

        if [ "x$PACKAGE_OVERWRITE" == "xy" -a -f "$install_file" ]; then
            log_verbose "overwritting file (PACKAGE_OVERWRITE) - $install_file"
            rm -f "$install_file"
        else
            log_verbose "installing file - $install_file"
        fi

        install $install_flags "$package_file" "$install_file"
        checksum=$($CHECKSUM_PROG "$install_file")
    else
        log_verbose "skipping file (PACKAGE_DB_ONLY) - $install_file"
        checksum='(null)'
    fi

    $BINDIR/package_query "$DATABASE" "$SQL_INSERT" \
            "$PACKAGE_NAME" "$TIMESTAMP" "$install_file" "file" "$checksum"

done < $FILE_CACHE_FILE

# vim: ts=4 sts=4 sw=4 et fdm=marker
# end of file
